### ISSUE TITLE
command line version returns error AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'

### ISSUE THREAD

**Issue by openclipboard** [quentinsf/pygarmin#11]
The installation of the latest via pip install pygarmin went fine.

Running on the command line, however, this is seen:

```
openclipboard@machine:~$ pygarmin
Traceback (most recent call last):
  File "/home/openclipboard/anaconda3/bin/pygarmin", line 5, in <module>
    from pygarmin.pygarmin import main
  File "/home/openclipboard/anaconda3/lib/python3.8/site-packages/pygarmin/pygarmin.py", line 1188, in <module>
    action=argparse.BooleanOptionalAction,
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
```

**Comment by fvdbeek** [comment]
The argparse.BooleanOptionalAction feature is only available in Python version 3.9 and above, so you should upgrade your Python distribution. I hadn't noticed this before, so Pygarmin required version 3.8 or above by mistake. This requirement is fixed now. Thank you for pointing this out.
