### ISSUE TITLE
Why isn't this in the Cheeseshop?

### ISSUE THREAD

**Issue by erikb85** [quentinsf/pygarmin#2]
Hi,

this project already has a setup.py which seems to be okay. Maybe you want to upload the current version to  [PyPI](https://pypi.python.org/) (e.g., like a [similar project did](https://pypi.python.org/pypi/pynmea2/1.4.0)). Then people can directly pip install your tool without having to find your github and without checking which is the most current and stable version.

**Comment by quentinsf** [comment]
Thanks Erik - that's a good idea - I'll take a look at this.  (I first wrote this long before pip and PyPI existed, and I don't think it works with recent devices, so I'm not sure how important it is any more, but I agree it's a good idea! - thanks)

Quentin

**Comment by erikb85** [comment]
Ah that's also a great info. Maybe then it's not necessary, yes. I thought you still use it, because it looks so well maintained.

**Comment by quentinsf** [comment]
Erik - a basic version is now there - there's probably lots of room for improvements in the way the package is set up if we wanted to modernise it completely!

**Comment by erikb85** [comment]
To tell you the truth, I think it's perfectly fine, just looking at your setup.py file. Thanks :+1:
