### ISSUE TITLE
Support for map upload?

### ISSUE THREAD

**Issue by jose1711** [quentinsf/pygarmin#3]
For my eTrex Legend the only way to upload map onto a device is via serial protocol (no mass storage). Since QLandkarteGT is discontinued there is practically no way of performing this task (other than tedious recompiling of QLandkarteGT with all its dependencies). Wonder if support for map upload could be added to this project. The communication is described in the sources of garmindev: https://sourceforge.net/projects/qlandkartegt/files/garmindev/Garmin%20Device%20Driver%200.3.4/

Thank you.

**Comment by quentinsf** [comment]
Hi Jose - 

I expect it could, but I'm afraid I haven't had a Garmin GPS for many years, and would have no way to test it.
But if you or anybody else wanted to write the code and submit a pull request, I'd be happy to take a look at it.

Best,
Quentin

**Comment by jose1711** [comment]
Hello Quentin,

thank you for your feedback. Adding it to `pygarmin` turned out to be too complex task for me so instead I took the relevant parts from your project (and also QLandkarte GT) and created a standalone script that works for me: https://github.com/jose1711/etrexlegend_mapupload that only does map upload and nothing else.

As this does the job for me I am closing the issue.

Thanks again, jose
